INSERT INTO TBL_EMPRESA (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (true,'Regional','(11) 91111-1111','Aqua Nutricao Vegetal');
INSERT INTO TBL_EMPRESA (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (false,'Regional','(11) 2222-2222','Ortiz Log Tramsportes');
INSERT INTO TBL_EMPRESA (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (true,'Nacional','(19) 93333-3333','Alfa Industria Metalurgica');
INSERT INTO TBL_EMPRESA (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (false,'Nacional','(19) 4444-4444','Aenge Engenharia Industrial');
INSERT INTO TBL_EMPRESA (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (true,'Internacional','+55 (11) 95555-5555','Pepsico');
INSERT INTO TBL_EMPRESA (ACTIVE,CATEGORY,CONTACT,NAME) VALUES (false,'Internacional','+55 (19) 6666-6666','Brasil Express');
